routes/web.php
<?php
use App\User;

	Route::get('insert_mahasiswa/{id}', function ($id) {
		if($id == '1'){
			\Artisan::call('insert:mahasiswa_1');
		}
		else if($id == '2'){
			\Artisan::call('insert:mahasiswa_2');
		}
		else if($id == '3'){
			\Artisan::call('insert:mahasiswa_3');
		}
		else if($id == '4'){
			\Artisan::call('insert:mahasiswa_4');
		}
		else if($id == '5'){
			\Artisan::call('insert:mahasiswa_5');
		}
		else if($id == '6'){
			\Artisan::call('insert:mahasiswa_6');
		}
		else if($id == 's2'){
			\Artisan::call('insert:mahasiswa_s2');
		}
	});

    Route::get('update_dosen', function () {
		\Artisan::call('update:dosen');
	});

    Route::get('update_akreditasi', function () {
        \Artisan::call('update:akreditasi');
    });

	Route::get('/', function () { return view('backend/login/index');	});

	Auth::routes();
	Route::any('pengguna/masuk', 'backend\masukController@masuk')->name('masuk');

	Route::group(['middleware' => [ 'auth']], function () {

	Route::get('/dashboard/{tahun?}', 'backend\Dashboard@index')->name('dashboard');

	# Periode
	Route::group([ 'prefix' => 'periode'], function () {
		Route::any('data', 'backend\periodeController@data')->name('periode.data');
		Route::post('{periode}/delete', 'backend\periodeController@destroy')->name('periode.delete');
	});
	Route::resource('periode', 'backend\periodeController');
	
	# User
	Route::group([ 'prefix' => 'user'], function () {
		Route::any('data', 'backend\UsersController@data')->name('user.data');
		Route::post('{user}/delete', 'backend\UsersController@destroy')->name('user.delete');
	});
	Route::resource('user', 'backend\UsersController');

	# Unit
	Route::group([ 'prefix' => 'unit'], function () {
		Route::any('data', 'backend\UnitController@data')->name('unit.data');
		Route::post('{unit}/delete', 'backend\UnitController@destroy')->name('unit.delete');
	});
	Route::resource('unit', 'backend\UnitController');

	# Dosen
	Route::group([ 'prefix' => 'dosen'], function () {
		Route::any('data', 'backend\dosenController@data')->name('dosen.data');
		Route::post('{dosen}/delete', 'backend\dosenController@destroy')->name('dosen.delete');
	});
	Route::resource('dosen', 'backend\dosenController');

	# Mahasiswa
	Route::group([ 'prefix' => 'mahasiswa'], function () {
		Route::any('data', 'backend\mahasiswaController@data')->name('mahasiswa.data');
        Route::post('{mahasiswa}/delete', 'backend\mahasiswaController@destroy')->name('mahasiswa.delete');

		Route::any('data_identitas', 'backend\mahasiswaController@data_identitas')->name('mahasiswa.data_identitas');
		Route::get('identitas', 'backend\mahasiswaController@index_identitas')->name('mahasiswa.index_identitas');
		Route::any('store_identitas/{id}', 'backend\mahasiswaController@store_identitas')->name('mahasiswa.store_identitas');
	});
	Route::resource('mahasiswa', 'backend\mahasiswaController');

	# SKPI
	Route::group([ 'prefix' => 'skpi'], function () {
		Route::any('data', 'backend\skpiController@data')->name('skpi.data');
		Route::any('data_skpinon', 'backend\skpiController@data_skpinon')->name('skpi.data_skpinon');
		Route::get('non', 'backend\skpiController@non')->name('skpi.non');
		Route::post('{skpi}/delete', 'backend\skpiController@destroy')->name('skpi.delete');
		Route::post('validasi', 'backend\skpiController@validasi')->name('skpi.validasi');
		Route::get('cetak/{skpi}', 'backend\skpiController@cetak_skpi')->name('skpi.cetak_skpi');
		Route::any('cetak_ex/{npm}/{dosen}', 'backend\skpiController@cetak_skpi_ex')->name('skpi.cetak_skpi_ex');
        Route::get('prestasi/{npm}', 'backend\skpiController@showPrestasi')->name('skpi.showPrestasi');


	});
	Route::resource('skpi', 'backend\skpiController');

	# capaian pembelajaran
	Route::group([ 'prefix' => 'capaian_pembelajaran'], function () {
		Route::any('data', 'backend\capaianPembelajaranController@data')->name('capaian_pembelajaran.data');
		Route::post('{capaian_pembelajaran}/delete', 'backend\capaianPembelajaranController@destroy')->name('capaian_pembelajaran.delete');
	});
	Route::resource('capaian_pembelajaran', 'backend\capaianPembelajaranController');

	# Prestasi
    Route::group([ 'prefix' => 'prestasi'], function () {
        Route::any('data', 'backend\prestasiController@data')->name('prestasi.data');
        Route::any('data_jenisprestasi', 'backend\prestasiController@data_jenisprestasi')->name('prestasi.data_jenisprestasi');
        Route::any('data_monitoring', 'backend\prestasiController@data_monitoring')->name('prestasi.data_monitoring');
        Route::any('data_rekapitulasi/{tahun?}', 'backend\prestasiController@data_rekapitulasi')->name('prestasi.data_rekapitulasi');
        Route::any('data_detail', 'backend\prestasiController@data_detail')->name('prestasi.data_detail');
        Route::any('data_validasi', 'backend\prestasiController@data_validasi')->name('prestasi.data_validasi');
        // Route::post('translate', 'backend\prestasiController@trans')->name('prestasi.trans');
        Route::get('translate/{npm}', 'backend\prestasiController@showTranslate')->name('prestasi.showTranslate');
        Route::post('simpan_translate/{npm}', 'backend\prestasiController@simpanTranslate')->name('prestasi.simpanTranslate');
        Route::post('{prestasi}/delete', 'backend\prestasiController@destroy')->name('prestasi.delete');
        Route::post('{prestasi}/approve', 'backend\prestasiController@approve')->name('prestasi.approve');
        Route::post('{prestasi}/approve_one', 'backend\prestasiController@approve_one')->name('prestasi.approve_one');
        Route::get('ambilFile/{prestasi}', 'backend\prestasiController@ambilFile')->name('prestasi.ambilFile');
        Route::get('akademik', 'backend\prestasiController@akademik')->name('prestasi.akademik');
        Route::get('nonakademik', 'backend\prestasiController@nonakademik')->name('prestasi.nonakademik');
        Route::get('validasi', 'backend\prestasiController@validasi_index')->name('prestasi.validasi_index');
        Route::get('monitoring', 'backend\prestasiController@monitoring_index')->name('prestasi.monitoring');
        Route::get('rekapitulasi_prodi/{tahun?}', 'backend\prestasiController@rekapitulasi_prodi')->name('prestasi.rekapitulasi_prodi');
    });
	Route::resource('prestasi', 'backend\prestasiController');
	Route::get('prestasi-input', 'backend\prestasiController@index')->name('prestasi-input');
	});

	Route::get('logout', 'Auth\LoginController@logout', function () {
    	return abort(404);
	});

	Route::get('skpi/unduh/{npm}/{id}/{nama?}/{file?}', 'backend\skpiController@unduh')->name('skpi.unduh');


Route::get('api_akreditasi', function() {
	return api_akreditasi();
});

Route::get('test_api/{npm}', function($npm) {
	return api_mahasiswa_by_npm($npm);
});

Route::get('api_mhs_limit_test/', function() {
	$alldata = array();
	// $data1 = api_mahasiswa_limit(0,5000);
	// $data2 = api_mahasiswa_limit(5001,10000);
	// $data3 = api_mahasiswa_limit(10001,15000);
	$data4 = api_mahasiswa_limit(15001,20000);
	$data5 = api_mahasiswa_limit(20001,25000);
	$data6 = api_mahasiswa_limit(25001,30000);
	// $alldata = array_merge($data, $data2);

	// decode json to array
	// $array[] = json_decode($data1, true);
	// $array[] = json_decode($data2, true);
	// $array[] = json_decode($data3, true);
	$array[] = json_decode($data4, true);
	$array[] = json_decode($data5, true);
	$array[] = json_decode($data6, true);

	// encode array to json
	$result = json_encode($array);
	$sumber = $result;
	$list = json_decode($sumber, true);
	return $list;
});
Route::get('test_api_skripsi/{npm}', function($npm) {
	return api_skripsi_by_npm($npm);
});
Route::get('api_skripsi_by_tahun/{tahun}', function($tahun) {
	return api_skripsi_by_tahun($tahun,1000,1100);
});
Route::get('test_api_mahasiswa/{npm}', function($npm) {
	return api_mahasiswa_by_npm($npm);
});

Route::get('api_mhs_limit/{awal}/{akhir}', function($awal,$akhir) {
	return api_mahasiswa_limit($awal,$akhir);
});

Route::get('test_api_mhs/{awal}/{akhir}', function($awal,$akhir) {
	return api_mahasiswa_all($awal,$akhir);
});

Route::get('test_api_s2/{npm}', function($npm) {
	return api_mahasiswa_by_npm_s2($npm);
});

Route::get('api_mhs_full_s2', function() {
	return api_mahasiswa_all_s2();
});

Route::get('test_api_mhs_s2/{awal}/{akhir}', function($awal,$akhir) {
	return api_mahasiswa_all_s2($awal,$akhir);
});

Route::get('test_mantra', function() {
	$d = new User();
	return $d->mantra('123510583');
});

Route::get('test_mantras2', function() {
	$d = new User();
	return $d->mantras2('187121043');
});

Route::get('lama_studi/{tgl_lulus}/{angkatan}', function($tgl_lulus,$angkatan) {
	return siswa_waktu($tgl_lulus, $angkatan);
});

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{

    protected $fillable = [
        'id',
        'nama_unit',
        'nama_unit_en',
        'parent_unit_id',
        'no_sk_unit',
        'tgl_sk_unit',
        'jenis_pendidikan',
        'dokumen_unit',
        'gelar',
        'gelar_en',
        'singkatan_gelar',
        'singkatan_gelar_en',
        'akreditasi',
        'no_sertifikat_akre',
        'dokumen_akre',
        'nidn_pimpinan',
        'dosen_id'

    ];

    public function capaian_pembelajaran()
    {
        return $this->belongsTo('App\CapaianPembelajaran', 'id');
    }

    public function dosen()
    {
        return $this->belongsTo('App\Dosen', 'dosen_id');
    }

    public function child()
    {
        return $this->hasMany('App\Unit', 'parent_unit_id')->with('parent');
    }

    public function parent()
    {
        return $this->belongsTo('App\Unit', 'parent_unit_id');
    }
    // static function addIdToQuery($query, $org)
    // {
    //     $query = $query->orWhere('id', 3);
    //     foreach ($org->subUnit as $org)
    //     {
    //         $query = Unit::addIdToQuery($query, $org);
    //     }
    //     return $query;
    // }

    // public function ambil_unit_with_child()
    // {
    //     $query = $this->subUnit();
    //     $query = Unit::addIdToQuery($query, $this);
    //     return $query;
    // }

}

app/Http/Controllers/backend/UsersController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Permission;
use App\User;
use App\Menu;
use App\Unit;
use Auth;
use File;
use Illuminate\Config;
use Illuminate\Http\Request;
use App\Http\Requests\userRequest;
use Redirect;
use View;
use Yajra\DataTables\DataTables;
use DB;
use Hash;

class UsersController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Grab all the data
        $data           = User::all();
        $permissions    = Permission::all();
        $units          = Unit::all();
        $title          = "User";
        // Show the page
        return view('backend.user.index', compact('data','title','permissions','units'));
    }

    public function data()
    {             
        $data = User::select(['id','name', 'email','permissions_id'])
                ->where('permissions_id', '<>', 5)
                ->orderBy('id', 'DESC')->get();
        return DataTables::of($data)
            ->editColumn('level',function(User $data) {
                return $data->permissionsGroup->permission_name;
            })
 
            ->addColumn('actions',function($data) {
                $actions = '<a onclick="editForm('.$data->id.')" class="btn btn-icon btn-neutral btn-icon-mini" title="Edit"><i class="zmdi zmdi-edit"></i></a>';
                if($data->id != Auth::user()->id){
                    $actions .= '<a onclick="deleteForm('.$data->id.')" class="btn btn-icon btn-neutral btn-icon-mini" title="Delete"><i class="zmdi zmdi-delete"></i></a>';

                }
              
                return $actions;
            })
            ->addIndexColumn()
            ->rawColumns(['actions','level'])
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function show($id)
    {
        $data = User::FindOrFail($id);    
        return json_encode($data);
    }

    
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(userRequest $request)
    {

        $data = new User();

        if ($file = $request->file('pic_file')) {
            $fullName=$file->getClientOriginalName();
            $name=explode('.',$fullName)[0];
    
            $originalImage = str_replace(str_split(',&\\/:;*?"<>|()." "'), '-', $name);
            $replaceImage=strtolower($originalImage);
    
            $gambarName = time().$replaceImage.'.'.$file->getClientOriginalExtension(); 
            // if(!file_exists( public_path() . 'backend/assets/images/users/'))
            // {
            //     File::makeDirectory( public_path() . 'backend/assets/images/users/');
            // }
            $destinationPath = 'backend/assets/images/users/';

            $file->move($destinationPath, $gambarName);
            $data->pic = $gambarName;
        }
        $data->name                 = $request->name;
        $data->email                = $request->email;
        $data->hp                   = $request->hp;
        $data->permissions_id       = $request->level;
        $data->unit_id              = $request->unit_id;
        $data->status               = 1;
        $data->created_by           = Auth::user()->id;
        $data->password             = bcrypt($request->password);

        return $data->save() ? 1 : 0;

        
    }


    public function edit($user)
    {
        
    }

    public function update(userRequest $request, $id)
    {

        $data = User::find($id);
        if ($file = $request->file('pic_file')) {
            $fullName=$file->getClientOriginalName();
            $name=explode('.',$fullName)[0];
    
            $originalImage = str_replace(str_split(',&\\/:;*?"<>|()." "'), '-', $name);
            $replaceImage=strtolower($originalImage);
    
            $gambarName = time().$replaceImage.'.'.$file->getClientOriginalExtension(); 
            // if(!file_exists( public_path() . 'backend/assets/images/users/'))
            // {
            //     File::makeDirectory( public_path() . 'backend/assets/images/users/');
            // }
            $destinationPath = 'backend/assets/images/users/';

            $file->move($destinationPath, $gambarName);
            $data->pic = $gambarName;
        }

        if($request->name){
            $data->name                 = $request->name;
        }

        if($request->email){
            $data->email                = $request->email;
        }
        
        if($request->hp){
            $data->hp                   = $request->hp;
        }

        if($request->level){
            $data->permissions_id       = $request->level;
        }

        if($request->unit_id){
            $data->unit_id              = $request->unit_id;
        }

        if($request->password){
            $data->password             = bcrypt($request->password);
        }
        $data->updated_by               = Auth::user()->id;
        

        return $data->update() ? 1 : 0;

    }

    public function destroy($id)
    {
        $data = User::find($id);
        return $data->delete() ? 1 : 0;
    }
}

app/Http/Controllers/backend/dosenController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Permission;
use App\User;
use App\Dosen;
use App\Unit;
use Auth;
use File;
use Illuminate\Config;
use App\Http\Requests\dosenRequest;
use Redirect;
use View;
use Yajra\DataTables\DataTables;
use DB;
use Hash;

class dosenController extends Controller
{
    public function index()
    {
        // Grab all the data
        $title                      = "Dosen";
        $dosens                     = Dosen::all();
        // Show the page
        return view('backend.dosen.index', compact('data','title','dosens'));
    }

    public function data()
    {
        if(request()->ajax()) {
            return datatables()->of(Dosen::select('*'))
            ->addIndexColumn()
            ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function show($id)
    {
        $data = Dosen::FindOrFail($id);    
        return json_encode($data);
    }

    
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(dosenRequest $request)
    {

     
    }


    public function edit($user)
    {
        
    }

    public function update(prestasiRequest $request, $id)
    {

        $data = Dosen::find($id);
    
        
        $data->nidn         = $request->nidn;
        $data->nama_dosen   = $request->nama_dosen;

        return $data->update() ? 1 : 0;

    }

    public function destroy($id)
    {
        $data = Dosen::find($id);

        return $data->delete() ? 1 : 0;
    }
}

resources/views/backend/unit/ajax.blade.php
<script type="text/javascript">
var table;
$(document).ready( function () {
        $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
        });
    table = $('#table').DataTable({
        processing: true,
        serverSide: true,
        ajax: {
          url: '{!! route('unit.data') !!}',
          type: 'POST'
         },
        columns: [
            { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false,searchable: false},
            { data: 'actions', name: 'actions', orderable: false, searchable: false },
            { data: 'nama_unit' },
            { data: 'no_sk_unit'},
            { data: 'tgl_sk_unit'},
            { data: 'jenis_pendidikan'},
            { data: 'dokumen_unit'},
            { data: 'gelar'},
            { data: 'singkatan_gelar'},
            { data: 'akreditasi'},
            { data: 'no_sertifikat_akre'},
            { data: 'dokumen_akre'},
            { data: 'pimpinan'},
        ]
    });
    table.on( 'draw', function () {
        $('.livicon').each(function(){
            $(this).updateLivicon();
        });
    } );
});


//OPEN MODAL EDIT
function editForm(id){
    save_method = "edit";
    $('input[name=_method]').val('PUT');
    $('#modal').modal('show');
    $('#modal .modal-title').text('Edit Unit');

    $("body").on("click",".clearCacheForm",function(){
            $(".refresh").empty();
            $(".refresh").attr('readonly',false);
    });
    $.ajax({
        url: "{{ url('unit') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {
                $('#id').val(data.id);
                $('#nama_unit').val(data.nama_unit).attr("readonly",true);
                $('#nama_unit_en').val(data.nama_unit_en);
                $('#no_sk_unit').val(data.no_sk_unit);
                $('#tgl_sk_unit').val(data.tgl_sk_unit);
                $('#gelar').val(data.gelar);
                $('#singkatan_gelar').val(data.singkatan_gelar);
                $('#gelar_en').val(data.gelar_en);
                $('#singkatan_gelar_en').val(data.singkatan_gelar_en);
                $('#akreditasi').val(data.akreditasi);
                $('#no_sertifikat_akre').val(data.no_sertifikat_akre);
                $("#nidn_pimpinan option[value='" + data.dosen_id + "']").prop("selected", true).change();

        },
        error: function() {
            alert('Data is empty !')
        }
    });
};

//OPEN MODAL DELETE
function deleteForm(id){
    swal({
            title: "Are you sure?",
            text: "You will not be able to recover this data!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            closeOnConfirm: false
            }, function () {
                    $.ajax({
                    headers: {'X-CSRF-TOKEN': $('#modal input[name="_token"]').val()},
                    type: "POST",
                    url: "{{ url('unit') }}"+'/'+id+"/delete",
                    timeout: 3000,
                    success : function(e) {
                        if (e = 1) {
                            ShowAlertDeletedWithReload();
                        }
                        else{
                            swal("Oops!", "Gagal Menghapus Data.", "warning");
                        }
                    },
                    error : function(e){
                        showErrorMessage();
                    }
                    });
            });
};


// End DELETE Function

$(function () {
	$('body').on('hidden.bs.modal', '.modal', function () {
		$(this).removeData('bs.modal');
	});
});

$('#btnSave').on('click', function (syabdan){
    if (!syabdan.isDefaultPrevented()){
            var id=$('#id').val();

            if (id == '') {
                var url  = "{{ route('unit.store') }}";
            }
            else
            {
                var url  = "{{  url('unit') }}"+'/'+id;
            }


            var form = $('#modal-form')[0];
            var inputData = new FormData(form);
            $.ajax({
                processData: false,
                contentType: false,
                cache: false,
                type: "POST",
                enctype: 'multipart/form-data',
                url: url,
                data: inputData,
                timeout: 600000,
                success : function(syabdan) {

                        document.getElementById("modal-form").reset();
                        showAjaxLoaderSuccesMessage();

                },
                error : function(syabdan){
                    if(syabdan['responseJSON']['errors']) {
                        if(syabdan['responseJSON']['errors']['nama_unit_en']){
                            $( '#nama_unit_en-Error' ).html(syabdan['responseJSON']['errors']['nama_unit_en'][0]);
                        }
                        if(syabdan['responseJSON']['errors']['gelar']){
                            $( '#gelar-Error' ).html(syabdan['responseJSON']['errors']['gelar'][0]);
                        }
                        if(syabdan['responseJSON']['errors']['gelar_en']){
                            $( '#gelar_en-Error' ).html(syabdan['responseJSON']['errors']['gelar_en'][0]);
                        }
                        if(syabdan['responseJSON']['errors']['singkatan_gelar']){
                            $( '#singkatan_gelar-Error' ).html(syabdan['responseJSON']['errors']['singkatan_gelar'][0]);
                        }
                        if(syabdan['responseJSON']['errors']['singkatan_gelar_en']){
                            $( '#singkatan_gelar_en-Error' ).html(syabdan['responseJSON']['errors']['singkatan_gelar_en'][0]);
                        }
                        if(syabdan['responseJSON']['errors']['nidn_pimpinan']){
                            $( '#nidn_pimpinan-Error' ).html(syabdan['responseJSON']['errors']['nidn_pimpinan'][0]);
                        }

                    }
                    showErrorMessage();
                }
            });
            return false;
        }
});


</script>

<script>
    $(function () {
        $('#tgl_sk_unit').bootstrapMaterialDatePicker({
            format: 'YYYY-MM-DD',
            time: false
        });
    });

    $(".select2").select2();

</script>

resources/views/backend/unit/index.blade.php
@extends('layouts.backend.app')
@section('title', 'Unit')
@section('header','Unit')
@section('subheader','Unit')
@section('bread') <a href="">Unit</a> @endsection

@push('style')
<link href="{{ asset('backend/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css')}}" rel="stylesheet" />
<link href="{{ asset('backend/assets/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />
<link rel="stylesheet" href="{{asset('backend/assets/plugins/footable-bootstrap/css/footable.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('backend/assets/plugins/footable-bootstrap/css/footable.standalone.min.css')}}">
<!-- JQuery DataTable Css -->
<link rel="stylesheet" href="{{ asset('backend/assets/plugins/jquery-datatable/dataTables.bootstrap4.min.css')}}">
<!-- Dropzone Css -->
<link rel="stylesheet" href="{{ asset('backend/assets/plugins/dropzone/dropzone.css')}}">

<link href="{{ asset('backend/vendors/select2/css/select2.min.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('backend/vendors/select2/css/select2-bootstrap.css') }}" rel="stylesheet">
@endpush
@push('scripthead')
@endpush
@section('content')
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <!-- <button type="button" class="btn btn-info btn-round waves-effect btn-sm align-right"  onclick="modal_add_show()"><i class="zmdi zmdi-plus "></i> Tambah</button> -->
                    </div>

                    <div class="card">
                    <div class="body table-responsive">
                        <table class="table table-hover m-b-0 c_list" id="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th data-breakpoints="sm xs md">Action</th>
                                    <th>Nama Unit</th>
                                    <th data-breakpoints="xs">No SK Unit</th>
                                    <th data-breakpoints="xs">Tgl SK Unit</th>
                                    <th data-breakpoints="xs">Jenis Pendidikan</th>
                                    <th data-breakpoints="xs">Dokumen Unit</th>
                                    <th data-breakpoints="xs">Gelar</th>
                                    <th data-breakpoints="xs">Singkatan Gelar</th>
                                    <th data-breakpoints="xs">Akreditasi</th>
                                    <th data-breakpoints="xs">No. Akreditasi</th>
                                    <th data-breakpoints="xs">Dokumen Akreditasi</th>
                                    <th data-breakpoints="xs">Pimpinan</th>
                                </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('modal')
	@include('backend.unit.form')
@endsection
@push('scriptbottom')
<script src="{{ asset('backend/assets/plugins/momentjs/moment.js')}}"></script>
<script src="{{ asset('backend/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js')}}"></script>
<script src="{{ asset('backend/assets/js/pages/forms/basic-form-elements.js')}}"></script>
<script src="{{ asset('backend/assets/bundles/footable.bundle.js')}}"></script>

<!-- Jquery DataTable Plugin Js -->
<script src="{{ asset('backend/assets/bundles/datatablescripts.bundle.js')}}"></script>
<script src="{{ asset('backend/assets/plugins/jquery-datatable/buttons/dataTables.buttons.min.js')}}"></script>
<script src="{{ asset('backend/assets/plugins/jquery-datatable/buttons/buttons.bootstrap4.min.js')}}"></script>
<script src="{{ asset('backend/assets/plugins/jquery-datatable/buttons/buttons.colVis.min.js')}}"></script>
<script src="{{ asset('backend/assets/plugins/jquery-datatable/buttons/buttons.html5.min.js')}}"></script>
<script src="{{ asset('backend/assets/plugins/jquery-datatable/buttons/buttons.print.min.js')}}"></script>

<script src="{{ asset('backend/assets/plugins/ckeditor/ckeditor.js')}}"></script> <!-- Ckeditor -->
<script src="{{ asset('backend/assets/plugins/ckeditor/config.js')}}"></script> <!-- Ckeditor -->

<script src="{{ asset('backend/vendors/select2/js/select2.js') }}" type="text/javascript"></script>

@include('backend.unit.ajax')

@endpush